name = "pb"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "txt.899366.xyz"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "cx238e9chen634aamoyux5eaxs4839"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://txt.899366.xyz"

# url to repo, displayed in the index page
REPO = "https://github.com/SharzyL/pastebin-worker"

# url to the favicon
FAVICON = "https://ipfs.mbzj.org/ipfs/QmQ7R2p9R5jicpkFUh3Tx86V7vQCP3F83xU3ANBnseKHuN.jpg"

# the name displayed in TOS
TOS_MAINTAINER = "WishEndDark"

# the email displayed in TOS
TOS_MAIL = "pb@WishEndDark"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
